### ISSUE TITLE
Not responding when sent data

### ISSUE THREAD

**Issue by onato** [Aconex/drakov#49]
I get the correct response from…

```
curl --request POST http://127.0.0.1:3000/login -H "noredirect: true"
```

…but not from…

```
curl --request POST --data 'username=username&password=password' http://127.0.0.1:3000/login -H "noredirect: true"
```
*Response: Cannot POST /login*

When I use the same API blueprint on app.apiary.io both request work. 

```
## Login [/login]

A Question object has the following attributes:

### Login [POST]

+ username (string) - A user name.
+ password (string) - A password.

+ Request

    + Headers
    
            noredirect: true
            
    + Body
    
            username=username&password=password

+ Response 200 (application/json)

            {"status":"ok"}
```

**Comment by yakovkhalinsky** [comment]
Hi @onato we'll do some testing and get back to you :+1:

**Comment by marcelogo** [comment]
@onato

we have found 2 situations in your case.

a. You should specify a media type on your blueprint file. Apparently curl defaults the request media type to `application/x-www-form-urlencoded`. Due to this, Drakov is unable to match the actual request with the spec request.

b. Snowcrash parses the body content with a new line at the end. This is one situation we believe to be addressable by Drakov. We will fix it and release in the next update.

**Comment by marcelogo** [comment]
A fix has been released.

Please test it and let us know how it goes.

**Comment by onato** [comment]
Now it works fine. Thanks for the impressively fast response.
