### ISSUE TITLE
Having issues with POST, PUT and DELETE

### ISSUE THREAD

**Issue by deanmraz** [Aconex/drakov#51]
Does the request methods POST/PUT/DELETE work? 

I've even tried setting up the example docs and couldn't get them to work. 
ie. sourceFiles: 'node_modules/drakov/test/example/md/**.md',

**Comment by yakovkhalinsky** [comment]
Hey @deanmraz sorry to hear your having trouble.

Are you running it as middleware or from the command line?

Can you paste in the command you are running?

**Comment by yakovkhalinsky** [comment]
Oh and any output you are getting would be useful as well, thanks

**Comment by deanmraz** [comment]
@yakovkhalinsky I've done both, started with the middleware and checked to see if the command line was working. Most of the GET methods work but haven't been able to run any POST, PUT or DELETE. 

I've even tested the examples in the test. The /api/multiple doesn't seem to work for both GET & POST, I get these errors: 
Cannot GET /api/multiple
Cannot POST /api/multiple

This is the command I ran: 
drakov -f "node_modules/drakov/test/example/md/multiple-examples-api.md"

Running: 
Node v0.10.32
Drakov 0.1.3

@yakovkhalinsky thanks for the help!

**Comment by marcelogo** [comment]
@deanmraz 

Please note that some headers are mandatory in order to get the response described in the md file.

The first `GET` requires a `Custom-header: First' to be set.

```
+ Request

    + Headers

        Custom-header: First
```


The same situation occurs for the `POST` method. Two things are required:

- The `Content-Type` header with `application/json` 
- The `body` with ` {"first": "example"}`

```
### Post to the first example [POST]

+ Request (application/json)
First POST example with body 

    + Body

        {"first": "example"}
```

Could you please check it and let us know how it goes? 

You can also refer to our tests. Note that `multiple-examples-api-test.js` sends all the required information on the requests.

**Comment by yakovkhalinsky** [comment]
@deanmraz how are you sending the POST, PUT and DELETE message?

Are you using curl or something like postman?

**Comment by deanmraz** [comment]
@yakovkhalinsky using postman

@marcelogo that was it, didn't have the right headers. 

Thank you both and much appreciated!
