### ISSUE TITLE
Parametric MD file

### ISSUE THREAD

**Issue by lucamartellucci** [Aconex/drakov#67]
Hi, i'm successfully using Drakov to mock my backend. Thank you for such useful tool!
I've just a question for you.. There is a way to program drakov to accept any date in a given field?
I've similar request body:

{"moneytransfer" : {"amount":200, "sender": "Luca", "receiver": "Mario", "transferDate": "03/07/2015"}}

Actually every day I use drakov I have to modify the .md file to update the transferDate field.. is it possible to write the .md file yust one time and say someting like: "transferDate": "any"

Thank you

Luca

**Comment by yakovkhalinsky** [comment]
Hey @lucamartellucci glad you are finding it useful :+1: 

Instead of having an exact match on the request body you can also use a schema to match, this will override the need to have an exact match on the request body.

There is an example here:
https://github.com/Aconex/drakov/blob/master/test/example/md/json-schema.md

You can also find more examples here:
http://json-schema.org/examples.html

**Comment by marcelogo** [comment]
@lucamartellucci 
Have you managed to use a json schema to address your scenario?

**Comment by marcelogo** [comment]
@lucamartellucci 

We've taken that your issue has been addressed and we are closing this question

Please get back to us if you still need help to sort it out.
